/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on 6 oct. 2009, 15:02:03
 */

package fr.enib.ihm.bookshop.app;

import fr.enib.ihm.bookshop.view.JCategoryPanel;
import fr.enib.ihm.bookshop.view.JCreateCustomerPanel;
import fr.enib.ihm.bookshop.view.JCreateOrderPanel;
import fr.enib.ihm.bookshop.view.JSubjectPanel;
import fr.enib.ihm.bookshop.view.JOrderPanel;
import fr.enib.ihm.bookshop.view.JCustomerPanel;
import fr.enib.ihm.bookshop.view.JBookPanel;
import fr.enib.ihm.bookshop.controller.Serializer;
import fr.enib.ihm.bookshop.view.subView.JClosePanel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.skin.BusinessBlackSteelSkin;

/**
 *
 * @author yo8chapa
 */
public class Main extends javax.swing.JFrame {

    /** Creates new form Main */
    public Main() {
        /* Modification du Look & Feel */
        SubstanceLookAndFeel.setSkin(new BusinessBlackSteelSkin());
        //https://substance.dev.java.net/docs/api/SetSkin_Instance.html
        //http://www.javootoo.com/plaf/skinlf/themepacks/index.html
        /*
         * Initialisation 
         */
        initComponents();
        Serializer.getInstance().deserialise();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        JImgEnib = new javax.swing.JLabel();
        jTabbedPanelMain = new javax.swing.JTabbedPane();
        jPanelAccueil = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMainMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemQuit = new javax.swing.JMenuItem();
        jMenuCustomer = new javax.swing.JMenu();
        jMenuItemAddCustomer = new javax.swing.JMenuItem();
        jMenuItemListCustomer = new javax.swing.JMenuItem();
        jMenuCatalog = new javax.swing.JMenu();
        jSubMenuList = new javax.swing.JMenu();
        jSubMenuListCat = new javax.swing.JMenuItem();
        jSubMenuListSub = new javax.swing.JMenuItem();
        jSubMenuListBoo = new javax.swing.JMenuItem();
        jMenuOrder = new javax.swing.JMenu();
        jMenuItemAddOrder = new javax.swing.JMenuItem();
        jMenuItemOrderList = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BookShop ENIB");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(880, 680));
        setName("MainFrame"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeAction(evt);
            }
        });

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHeader.setOpaque(false);
        jPanelHeader.setLayout(new java.awt.BorderLayout());

        JImgEnib.setBackground(new java.awt.Color(255, 255, 255));
        JImgEnib.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JImgEnib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/bookShopHeader.png"))); // NOI18N
        JImgEnib.setAlignmentY(0.0F);
        JImgEnib.setFocusable(false);
        jPanelHeader.add(JImgEnib, java.awt.BorderLayout.CENTER);

        jTabbedPanelMain.setName("accueil"); // NOI18N

        jPanelAccueil.setBackground(new java.awt.Color(207, 218, 241));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Edito"));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Bienvenue sur l'interface de gestion de livres \"Enib BookShop\".");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setText(" Cette interface est conçu pour permettre la gestion d'une liste de livre et des bons de commandes associés.");

        jLabel3.setText("La navigation par onglet est faite pour augmenter la facilité d'utilisation.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelAccueilLayout = new javax.swing.GroupLayout(jPanelAccueil);
        jPanelAccueil.setLayout(jPanelAccueilLayout);
        jPanelAccueilLayout.setHorizontalGroup(
            jPanelAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccueilLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanelAccueilLayout.setVerticalGroup(
            jPanelAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccueilLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        jTabbedPanelMain.addTab("Accueil", jPanelAccueil);

        jMenuFile.setText("File");

        jMenuItemQuit.setText("Quit");
        jMenuItemQuit.setToolTipText("Exit the application");
        jMenuItemQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemQuit);

        jMainMenuBar.add(jMenuFile);

        jMenuCustomer.setText("Customer");

        jMenuItemAddCustomer.setText("Add customer");
        jMenuItemAddCustomer.setToolTipText("Add a new customer");
        jMenuItemAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddCustomerActionPerformed(evt);
            }
        });
        jMenuCustomer.add(jMenuItemAddCustomer);

        jMenuItemListCustomer.setText("Customer list");
        jMenuItemListCustomer.setToolTipText("view customer list");
        jMenuItemListCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListCustomerActionPerformed(evt);
            }
        });
        jMenuCustomer.add(jMenuItemListCustomer);

        jMainMenuBar.add(jMenuCustomer);

        jMenuCatalog.setText("Catalog");

        jSubMenuList.setText("List");

        jSubMenuListCat.setText("Categories");
        jSubMenuListCat.setToolTipText("Edit categories");
        jSubMenuListCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuListCatActionPerformed(evt);
            }
        });
        jSubMenuList.add(jSubMenuListCat);

        jSubMenuListSub.setText("Subjects");
        jSubMenuListSub.setToolTipText("Edit subjects");
        jSubMenuListSub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSubMenuListSubMouseClicked(evt);
            }
        });
        jSubMenuListSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuListSubActionPerformed(evt);
            }
        });
        jSubMenuList.add(jSubMenuListSub);

        jSubMenuListBoo.setText("Books");
        jSubMenuListBoo.setToolTipText("Edit books");
        jSubMenuListBoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuListBooActionPerformed(evt);
            }
        });
        jSubMenuList.add(jSubMenuListBoo);

        jMenuCatalog.add(jSubMenuList);

        jMainMenuBar.add(jMenuCatalog);

        jMenuOrder.setText("Order");

        jMenuItemAddOrder.setText("Add Order");
        jMenuItemAddOrder.setToolTipText("Add an order");
        jMenuItemAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddOrderActionPerformed(evt);
            }
        });
        jMenuOrder.add(jMenuItemAddOrder);

        jMenuItemOrderList.setText("Order list");
        jMenuItemOrderList.setToolTipText("View order list");
        jMenuItemOrderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOrderListActionPerformed(evt);
            }
        });
        jMenuOrder.add(jMenuItemOrderList);

        jMainMenuBar.add(jMenuOrder);

        setJMenuBar(jMainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPanelMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                    .addComponent(jPanelHeader, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSubMenuListCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuListCatActionPerformed
        createPanel(jTabbedPanelMain, new String("Category"), new JCategoryPanel());
}//GEN-LAST:event_jSubMenuListCatActionPerformed

    private void jSubMenuListSubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSubMenuListSubMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jSubMenuListSubMouseClicked

    private void jSubMenuListSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuListSubActionPerformed
        createPanel(jTabbedPanelMain, new String("Subject"), new JSubjectPanel());
    }//GEN-LAST:event_jSubMenuListSubActionPerformed

    private void jSubMenuListBooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuListBooActionPerformed
        createPanel(jTabbedPanelMain, new String("Book"), new JBookPanel());
    }//GEN-LAST:event_jSubMenuListBooActionPerformed

    private void jMenuItemAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddCustomerActionPerformed
        createPanel(jTabbedPanelMain, new String("Add customer"), new JCreateCustomerPanel());
    }//GEN-LAST:event_jMenuItemAddCustomerActionPerformed

    private void jMenuItemListCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListCustomerActionPerformed
        createPanel(jTabbedPanelMain, new String("Customer"), new JCustomerPanel());
    }//GEN-LAST:event_jMenuItemListCustomerActionPerformed

    private void jMenuItemAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddOrderActionPerformed
        createPanel(jTabbedPanelMain, new String("Add order"), new JCreateOrderPanel());
    }//GEN-LAST:event_jMenuItemAddOrderActionPerformed

    private void jMenuItemOrderListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOrderListActionPerformed
        createPanel(jTabbedPanelMain, new String("Order"), new JOrderPanel());
    }//GEN-LAST:event_jMenuItemOrderListActionPerformed

    private void jMenuItemQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitActionPerformed
       dispose();
       this.closeAction();
       System.exit(0);
    }//GEN-LAST:event_jMenuItemQuitActionPerformed

    private void closeAction(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeAction
        this.closeAction();
    }//GEN-LAST:event_closeAction
    /*
     * Creation d'un Closepanel associé au menu cliqué
     * -- Ce panel contient le panel correspondant
     *
     */
    public void createPanel(JTabbedPane tabbedPanel, String panelTitle, JPanel panelName){
        int compteur = 0;
        for(int i = 0; i < tabbedPanel.getComponentCount(); i++){        
            if(tabbedPanel.getComponents()[i].getName() != null){
                if(tabbedPanel.getComponents()[i].getName().equals(panelTitle)){
                    compteur++;
                }
            }
        }
        if(compteur == 0){
            new JClosePanel(panelTitle, tabbedPanel, panelName);
            tabbedPanel.setSelectedIndex(tabbedPanel.indexOfComponent(panelName)); //Focus
        }
    }
    /*
     *
     * closeAction()
     * Actions à la fermeture de l'application
     *
     */
    public void closeAction(){
        Serializer.getInstance().serialise();
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JImgEnib;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMainMenuBar;
    private javax.swing.JMenu jMenuCatalog;
    private javax.swing.JMenu jMenuCustomer;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemAddCustomer;
    private javax.swing.JMenuItem jMenuItemAddOrder;
    private javax.swing.JMenuItem jMenuItemListCustomer;
    private javax.swing.JMenuItem jMenuItemOrderList;
    private javax.swing.JMenuItem jMenuItemQuit;
    private javax.swing.JMenu jMenuOrder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAccueil;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JMenu jSubMenuList;
    private javax.swing.JMenuItem jSubMenuListBoo;
    private javax.swing.JMenuItem jSubMenuListCat;
    private javax.swing.JMenuItem jSubMenuListSub;
    private javax.swing.JTabbedPane jTabbedPanelMain;
    // End of variables declaration//GEN-END:variables

}
