/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JEditBookPanel.java
 *
 * Created on 14 oct. 2009, 11:46:50
 */

package fr.enib.ihm.bookshop.view;

import com.toedter.calendar.JDateChooser;
import fr.enib.ihm.bookshop.controller.ApplicationEventsDispatcher;
import fr.enib.ihm.bookshop.controller.Books;
import fr.enib.ihm.bookshop.controller.Customers;
import fr.enib.ihm.bookshop.controller.events.OrderEvent;
import fr.enib.ihm.bookshop.domain.catalog.Book;
import fr.enib.ihm.bookshop.domain.customer.Address;
import fr.enib.ihm.bookshop.domain.customer.CreditCard;
import fr.enib.ihm.bookshop.domain.customer.Customer;
import fr.enib.ihm.bookshop.domain.order.Order;
import fr.enib.ihm.bookshop.domain.order.OrderLine;
import fr.enib.ihm.bookshop.view.subView.JClosePanel;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author yo8chapa
 */
public class JCreateOrderPanel extends javax.swing.JPanel {

    /** Creates new form JAddCustomerPanel */
    public JCreateOrderPanel() {
        initComponents();
        /*
         * Initialisation
         */
        // -- Panel hidden
        calendarExpCardDate = new JDateChooser("dd/MM/yyyy", "##/##/####", '_');
        calendarExpCardDate.setDate(new Date());
        jPanelDateCardChooser2.add(calendarExpCardDate);
        buttonGroupAddress.setSelected(jRadioButtonCustomerAddress.getModel(), true);
        buttonGroupCreditCard.setSelected(jRadioButtonCustomerCard.getModel(), true);        
        displayAddressFields(false);
        displayCardFields(false);
        // -- Customer list
        for(Customer c : Customers.getCustomers().getCustomersList())
            jComboBoxCustomer.addItem(c);
        // -- Book list
        for(Book b : Books.getInstance().getBooks())
            jComboBoxBook.addItem(b);
        // -- Order list
        jListOrders.setListData(orderList);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAddress = new javax.swing.ButtonGroup();
        buttonGroupCreditCard = new javax.swing.ButtonGroup();
        jLbLTitleNorth = new javax.swing.JLabel();
        jPanelFooter = new javax.swing.JPanel();
        jPanelForm = new javax.swing.JPanel();
        jPanelBuyInformation = new javax.swing.JPanel();
        jPanelCreditCard2 = new javax.swing.JPanel();
        jLabelCardNumber2 = new javax.swing.JLabel();
        jTextCardNumber2 = new javax.swing.JTextField();
        jTextCardType2 = new javax.swing.JTextField();
        jLabelCardType2 = new javax.swing.JLabel();
        jLabelCardExpiration2 = new javax.swing.JLabel();
        jPanelDateCardChooser2 = new javax.swing.JPanel();
        jPanelBtRadioCard = new javax.swing.JPanel();
        jRadioButtonCustomerCard = new javax.swing.JRadioButton();
        jRadioButtonSpecifCard = new javax.swing.JRadioButton();
        jPanelAdress = new javax.swing.JPanel();
        jLabelStreet = new javax.swing.JLabel();
        jTextStreet = new javax.swing.JTextField();
        jLabelCity = new javax.swing.JLabel();
        jTextCity = new javax.swing.JTextField();
        jLabelZcode = new javax.swing.JLabel();
        jTextZcode = new javax.swing.JTextField();
        jLabelCountry = new javax.swing.JLabel();
        jTextCountry = new javax.swing.JTextField();
        jLabelStreetNumber = new javax.swing.JLabel();
        jTextStreetNumber = new javax.swing.JTextField();
        jPanelBtAddress = new javax.swing.JPanel();
        jRadioButtonCustomerAddress = new javax.swing.JRadioButton();
        jRadioButtonSpecificAddress = new javax.swing.JRadioButton();
        jComboBoxCustomer = new javax.swing.JComboBox();
        jLabelCustomer = new javax.swing.JLabel();
        jButtonReadCustomer = new javax.swing.JButton();
        jPanelClose = new javax.swing.JPanel();
        jButtonCreate = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jPanelOrder = new javax.swing.JPanel();
        jPanelOrderLine = new javax.swing.JPanel();
        jComboBoxBook = new javax.swing.JComboBox();
        jTextQuantity = new javax.swing.JTextField();
        jLabelBook = new javax.swing.JLabel();
        jLabelQuantity = new javax.swing.JLabel();
        jButtonAddOrder = new javax.swing.JButton();
        jPanelListOrderLine = new javax.swing.JPanel();
        jScrollPaneOrders = new javax.swing.JScrollPane();
        jListOrders = new javax.swing.JList();
        jButtonRemoveOrderLine = new javax.swing.JButton();

        setName("JMainPanel"); // NOI18N
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jLbLTitleNorth.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLbLTitleNorth.setText("Create an order");
        jLbLTitleNorth.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(jLbLTitleNorth, java.awt.BorderLayout.NORTH);

        jPanelFooter.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelFooter.setOpaque(false);
        jPanelFooter.setLayout(new javax.swing.BoxLayout(jPanelFooter, javax.swing.BoxLayout.X_AXIS));
        add(jPanelFooter, java.awt.BorderLayout.SOUTH);

        jPanelForm.setOpaque(false);

        jPanelBuyInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "delivery's information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanelBuyInformation.setOpaque(false);

        jPanelCreditCard2.setBackground(new java.awt.Color(204, 204, 204));
        jPanelCreditCard2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Credit card ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabelCardNumber2.setText("Card number :");

        jLabelCardType2.setText("Type :");

        jLabelCardExpiration2.setText("Date expiration :");

        jPanelDateCardChooser2.setFocusable(false);
        jPanelDateCardChooser2.setMaximumSize(new java.awt.Dimension(145, 15));
        jPanelDateCardChooser2.setOpaque(false);
        jPanelDateCardChooser2.setLayout(new java.awt.BorderLayout());

        jPanelBtRadioCard.setOpaque(false);

        buttonGroupCreditCard.add(jRadioButtonCustomerCard);
        jRadioButtonCustomerCard.setText("Customer's credit card");
        jRadioButtonCustomerCard.setOpaque(false);
        jRadioButtonCustomerCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCustomerCardActionPerformed(evt);
            }
        });

        buttonGroupCreditCard.add(jRadioButtonSpecifCard);
        jRadioButtonSpecifCard.setText("Specific credit card");
        jRadioButtonSpecifCard.setOpaque(false);
        jRadioButtonSpecifCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSpecifCardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtRadioCardLayout = new javax.swing.GroupLayout(jPanelBtRadioCard);
        jPanelBtRadioCard.setLayout(jPanelBtRadioCardLayout);
        jPanelBtRadioCardLayout.setHorizontalGroup(
            jPanelBtRadioCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtRadioCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonCustomerCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonSpecifCard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBtRadioCardLayout.setVerticalGroup(
            jPanelBtRadioCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtRadioCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBtRadioCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCustomerCard)
                    .addComponent(jRadioButtonSpecifCard))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCreditCard2Layout = new javax.swing.GroupLayout(jPanelCreditCard2);
        jPanelCreditCard2.setLayout(jPanelCreditCard2Layout);
        jPanelCreditCard2Layout.setHorizontalGroup(
            jPanelCreditCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreditCard2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCreditCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBtRadioCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCreditCard2Layout.createSequentialGroup()
                        .addGroup(jPanelCreditCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCardExpiration2)
                            .addGroup(jPanelCreditCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelCardType2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCardNumber2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCreditCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCardNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCardType2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelDateCardChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelCreditCard2Layout.setVerticalGroup(
            jPanelCreditCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreditCard2Layout.createSequentialGroup()
                .addComponent(jPanelBtRadioCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCreditCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCardNumber2)
                    .addComponent(jTextCardNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCreditCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCardType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCardType2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreditCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCardExpiration2)
                    .addComponent(jPanelDateCardChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanelAdress.setBackground(new java.awt.Color(204, 204, 204));
        jPanelAdress.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Adress ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabelStreet.setText("Street :");

        jLabelCity.setText("City :");

        jLabelZcode.setText("Zip code :");

        jLabelCountry.setText("Country");

        jLabelStreetNumber.setText("Number :");

        jPanelBtAddress.setOpaque(false);

        buttonGroupAddress.add(jRadioButtonCustomerAddress);
        jRadioButtonCustomerAddress.setText("Customer's address");
        jRadioButtonCustomerAddress.setOpaque(false);
        jRadioButtonCustomerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCustomerAddressActionPerformed(evt);
            }
        });

        buttonGroupAddress.add(jRadioButtonSpecificAddress);
        jRadioButtonSpecificAddress.setText("Specific address");
        jRadioButtonSpecificAddress.setOpaque(false);
        jRadioButtonSpecificAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSpecificAddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtAddressLayout = new javax.swing.GroupLayout(jPanelBtAddress);
        jPanelBtAddress.setLayout(jPanelBtAddressLayout);
        jPanelBtAddressLayout.setHorizontalGroup(
            jPanelBtAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtAddressLayout.createSequentialGroup()
                .addComponent(jRadioButtonCustomerAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonSpecificAddress)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanelBtAddressLayout.setVerticalGroup(
            jPanelBtAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtAddressLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBtAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCustomerAddress)
                    .addComponent(jRadioButtonSpecificAddress)))
        );

        javax.swing.GroupLayout jPanelAdressLayout = new javax.swing.GroupLayout(jPanelAdress);
        jPanelAdress.setLayout(jPanelAdressLayout);
        jPanelAdressLayout.setHorizontalGroup(
            jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAdressLayout.createSequentialGroup()
                        .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStreet)
                            .addComponent(jLabelCountry)
                            .addComponent(jLabelCity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCountry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(jTextCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(jTextStreet, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelZcode)
                            .addComponent(jLabelStreetNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextZcode)
                            .addComponent(jTextStreetNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelAdressLayout.setVerticalGroup(
            jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdressLayout.createSequentialGroup()
                .addComponent(jPanelBtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStreet)
                    .addComponent(jTextStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextStreetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStreetNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCity)
                    .addComponent(jTextCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextZcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelZcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCountry)
                    .addComponent(jTextCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        jComboBoxCustomer.setToolTipText("customer");

        jLabelCustomer.setText("Customer : ");

        jButtonReadCustomer.setText("See customer's data");
        jButtonReadCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonReadCustomerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuyInformationLayout = new javax.swing.GroupLayout(jPanelBuyInformation);
        jPanelBuyInformation.setLayout(jPanelBuyInformationLayout);
        jPanelBuyInformationLayout.setHorizontalGroup(
            jPanelBuyInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuyInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuyInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAdress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCreditCard2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelBuyInformationLayout.createSequentialGroup()
                        .addComponent(jLabelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonReadCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelBuyInformationLayout.setVerticalGroup(
            jPanelBuyInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuyInformationLayout.createSequentialGroup()
                .addGroup(jPanelBuyInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCustomer)
                    .addComponent(jComboBoxCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReadCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCreditCard2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelClose.setOpaque(false);
        jPanelClose.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonCreate.setText("Create");
        jButtonCreate.setToolTipText("Create a customer");
        jButtonCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCreateMouseClicked(evt);
            }
        });
        jPanelClose.add(jButtonCreate);

        jButtonClose.setText("Close");
        jButtonClose.setToolTipText("Close this panel");
        jButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseClicked(evt);
            }
        });
        jPanelClose.add(jButtonClose);

        jPanelOrder.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Order ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jPanelOrderLine.setBackground(new java.awt.Color(204, 204, 204));
        jPanelOrderLine.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Order line ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTextQuantity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabelBook.setText("Book : ");

        jLabelQuantity.setText("Quantity :");

        jButtonAddOrder.setText("Add to order");
        jButtonAddOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddOrderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelOrderLineLayout = new javax.swing.GroupLayout(jPanelOrderLine);
        jPanelOrderLine.setLayout(jPanelOrderLineLayout);
        jPanelOrderLineLayout.setHorizontalGroup(
            jPanelOrderLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrderLineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOrderLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOrderLineLayout.createSequentialGroup()
                        .addGroup(jPanelOrderLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBook)
                            .addComponent(jLabelQuantity))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelOrderLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jComboBoxBook, 0, 118, Short.MAX_VALUE)))
                    .addComponent(jButtonAddOrder, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelOrderLineLayout.setVerticalGroup(
            jPanelOrderLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrderLineLayout.createSequentialGroup()
                .addGroup(jPanelOrderLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBook))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOrderLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddOrder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jListOrders.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListOrders.setToolTipText("Order line's list");
        jScrollPaneOrders.setViewportView(jListOrders);

        jButtonRemoveOrderLine.setText("Remove from order");
        jButtonRemoveOrderLine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRemoveOrderLineMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelListOrderLineLayout = new javax.swing.GroupLayout(jPanelListOrderLine);
        jPanelListOrderLine.setLayout(jPanelListOrderLineLayout);
        jPanelListOrderLineLayout.setHorizontalGroup(
            jPanelListOrderLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListOrderLineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListOrderLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneOrders, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jButtonRemoveOrderLine))
                .addContainerGap())
        );
        jPanelListOrderLineLayout.setVerticalGroup(
            jPanelListOrderLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListOrderLineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRemoveOrderLine)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelOrderLayout = new javax.swing.GroupLayout(jPanelOrder);
        jPanelOrder.setLayout(jPanelOrderLayout);
        jPanelOrderLayout.setHorizontalGroup(
            jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelListOrderLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelOrderLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelOrderLayout.setVerticalGroup(
            jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrderLayout.createSequentialGroup()
                .addComponent(jPanelOrderLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanelListOrderLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelFormLayout = new javax.swing.GroupLayout(jPanelForm);
        jPanelForm.setLayout(jPanelFormLayout);
        jPanelFormLayout.setHorizontalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addComponent(jPanelBuyInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanelOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelFormLayout.setVerticalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelBuyInformation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );

        add(jPanelForm, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreateMouseClicked
            Boolean check = true;
            Address deliveryAddress = null;
            CreditCard customerCard = null;
            Customer customerSelectionnated = (Customer) jComboBoxCustomer.getSelectedItem();
            // -- Définition de l'adresse
            if(buttonGroupAddress.isSelected(jRadioButtonCustomerAddress.getModel()) ){
                deliveryAddress = customerSelectionnated.getAddress();
            }else{
                int streetNumber = 0;
                if(!jTextStreetNumber.getText().isEmpty())  streetNumber = Integer.valueOf(jTextStreetNumber.getText());
                deliveryAddress = new Address( streetNumber, jTextStreet.getText(),
                                                  jTextCity.getText(), jTextZcode.getText(), jTextCountry.getText());
            }
            // -- Creditcard
            if(buttonGroupCreditCard.isSelected(jRadioButtonCustomerCard.getModel())){ 
                customerCard = customerSelectionnated.getCreditCard();
            }else{
                if(verifyCustomerCard() == true){                  
                    customerCard = new CreditCard();
                    customerCard.setCreditCardNumber(jTextCardNumber2.getText());
                    customerCard.setCreditCardType(jTextCardType2.getText());
                    SimpleDateFormat d = new SimpleDateFormat ("dd/MM/yyyy" );
                    String dateString = d.format(this.calendarExpCardDate.getDate());
                    customerCard.setCreditCardExpDate(dateString);
                }else{
                    check = false;
                }
            }
            if(check == true){
                // -- Order
                Order order = new Order(new Date(), customerSelectionnated, deliveryAddress, orderList);
                order.setCreditCard(customerCard);
                // -- Tirage d'évenement
                ApplicationEventsDispatcher.getApplicationEventsDispatcher().fireAddOrderEvent(new OrderEvent(evt, order));
                this.getParent().remove(this); // Close panel
            }
}//GEN-LAST:event_jButtonCreateMouseClicked
    private void displayAddressFields(Boolean b){
        jTextStreet.setEnabled(b);
        jTextStreetNumber.setEnabled(b);
        jTextCity.setEnabled(b);
        jTextCountry.setEnabled(b);
        jTextZcode.setEnabled(b);
    }
    private void displayCardFields(Boolean b){
        jTextCardNumber2.setEnabled(b);
        jTextCardType2.setEnabled(b);
        calendarExpCardDate.setEnabled(b);
    }
    private void jButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseClicked
        this.getParent().remove(this); // Close panel
    }//GEN-LAST:event_jButtonCloseMouseClicked

    private void jRadioButtonCustomerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCustomerAddressActionPerformed
        displayAddressFields(false);
    }//GEN-LAST:event_jRadioButtonCustomerAddressActionPerformed

    private void jRadioButtonSpecificAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSpecificAddressActionPerformed
        displayAddressFields(true);
    }//GEN-LAST:event_jRadioButtonSpecificAddressActionPerformed

    private void jRadioButtonCustomerCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCustomerCardActionPerformed
        displayCardFields(false);
    }//GEN-LAST:event_jRadioButtonCustomerCardActionPerformed

    private void jRadioButtonSpecifCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSpecifCardActionPerformed
        displayCardFields(true);
    }//GEN-LAST:event_jRadioButtonSpecifCardActionPerformed

    private void jButtonReadCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReadCustomerMouseClicked
        Customer customerSelectionnated = (Customer) jComboBoxCustomer.getSelectedItem();
        JPanel readPanel = new JReadCustomerPanel(customerSelectionnated);
        JTabbedPane tabbedPane = (JTabbedPane) getParent();
        new JClosePanel("Customer's data",tabbedPane, readPanel);
        tabbedPane.setSelectedIndex(tabbedPane.indexOfComponent(readPanel));
    }//GEN-LAST:event_jButtonReadCustomerMouseClicked

    private void jButtonAddOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddOrderMouseClicked
        Book bookSelectionnated = (Book)jComboBoxBook.getSelectedItem();
        if(verifyField(jTextQuantity)){
            int quantity = Integer.valueOf(jTextQuantity.getText());
            if(quantity > 0){
                OrderLine orderline = new OrderLine(quantity, bookSelectionnated);
                orderList.add(orderline);
                jListOrders.updateUI();
                jTextQuantity.setText("");
            }
        }        
    }//GEN-LAST:event_jButtonAddOrderMouseClicked

    private void jButtonRemoveOrderLineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemoveOrderLineMouseClicked
        OrderLine orderline = (OrderLine)jListOrders.getSelectedValue();
        orderList.remove(orderline);
        jListOrders.updateUI();
    }//GEN-LAST:event_jButtonRemoveOrderLineMouseClicked

    // -- Verifications
     private Boolean verifyCustomerCard(){
         Boolean retour = true;
         Date today = new Date();
         if(!calendarExpCardDate.getDate().after(today)){
            calendarExpCardDate.setBorder(BorderFactory.createLineBorder(Color.RED));
            retour &= false;
         }else {
             calendarExpCardDate.setBorder(BorderFactory.createLineBorder(Color.GREEN));
         }
         retour &= verifyField(jTextCardNumber2);
         return retour;
     }
    //
    private Boolean verifyField(JTextField name){
         if(name.getText().isEmpty() == true){
            name.setBorder(BorderFactory.createLineBorder(Color.RED));
            return new Boolean(false);
        }
        else{             
             name.setBorder(BorderFactory.createLineBorder(Color.BLACK));
             return new Boolean(true);
         }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAddress;
    private javax.swing.ButtonGroup buttonGroupCreditCard;
    private javax.swing.JButton jButtonAddOrder;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonReadCustomer;
    private javax.swing.JButton jButtonRemoveOrderLine;
    private javax.swing.JComboBox jComboBoxBook;
    private javax.swing.JComboBox jComboBoxCustomer;
    private javax.swing.JLabel jLabelBook;
    private javax.swing.JLabel jLabelCardExpiration2;
    private javax.swing.JLabel jLabelCardNumber2;
    private javax.swing.JLabel jLabelCardType2;
    private javax.swing.JLabel jLabelCity;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelCustomer;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelStreet;
    private javax.swing.JLabel jLabelStreetNumber;
    private javax.swing.JLabel jLabelZcode;
    private javax.swing.JLabel jLbLTitleNorth;
    private javax.swing.JList jListOrders;
    private javax.swing.JPanel jPanelAdress;
    private javax.swing.JPanel jPanelBtAddress;
    private javax.swing.JPanel jPanelBtRadioCard;
    private javax.swing.JPanel jPanelBuyInformation;
    private javax.swing.JPanel jPanelClose;
    private javax.swing.JPanel jPanelCreditCard2;
    private javax.swing.JPanel jPanelDateCardChooser2;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JPanel jPanelListOrderLine;
    private javax.swing.JPanel jPanelOrder;
    private javax.swing.JPanel jPanelOrderLine;
    private javax.swing.JRadioButton jRadioButtonCustomerAddress;
    private javax.swing.JRadioButton jRadioButtonCustomerCard;
    private javax.swing.JRadioButton jRadioButtonSpecifCard;
    private javax.swing.JRadioButton jRadioButtonSpecificAddress;
    private javax.swing.JScrollPane jScrollPaneOrders;
    private javax.swing.JTextField jTextCardNumber2;
    private javax.swing.JTextField jTextCardType2;
    private javax.swing.JTextField jTextCity;
    private javax.swing.JTextField jTextCountry;
    private javax.swing.JTextField jTextQuantity;
    private javax.swing.JTextField jTextStreet;
    private javax.swing.JTextField jTextStreetNumber;
    private javax.swing.JTextField jTextZcode;
    // End of variables declaration//GEN-END:variables
    private JDateChooser calendarExpCardDate;
    private Vector orderList = new Vector();
}
