/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JCreateSubjectPanel.java
 *
 * Created on 20 oct. 2009, 00:49:06
 */
package fr.enib.ihm.bookshop.view;

import fr.enib.ihm.bookshop.controller.ApplicationEventsDispatcher;
import fr.enib.ihm.bookshop.controller.Categories;
import fr.enib.ihm.bookshop.controller.Subjects;
import fr.enib.ihm.bookshop.controller.events.SubjectEvent;
import fr.enib.ihm.bookshop.domain.catalog.Category;
import fr.enib.ihm.bookshop.domain.catalog.Subject;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JTextField;

/**
 *
 * @author Yoann
 */
public class JCreateSubjectPanel extends javax.swing.JPanel {

    /** Creates new form JCreateSubjectPanel */
    public JCreateSubjectPanel() {
        initComponents();
        for (Category c : Categories.getInstance().getCategories()) {
            jComboBoxCategory.addItem(c);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabellTitle = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jButtonAdd = new javax.swing.JButton();
        jLabelCategoryAssociate = new javax.swing.JLabel();
        jComboBoxCategory = new javax.swing.JComboBox();
        jButtonClose = new javax.swing.JButton();

        jLabellTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabellTitle.setText("Create a subject");

        jLabelDescription.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabelDescription.setText("Description :");

        jLabelName.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabelName.setText("Name : ");

        jTextName.setToolTipText("Name of the subject");

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jTextAreaDescription.setToolTipText("Description of the subject");
        jScrollPane1.setViewportView(jTextAreaDescription);

        jButtonAdd.setText("Add");
        jButtonAdd.setToolTipText("Add a new subject");
        jButtonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddMouseClicked(evt);
            }
        });

        jLabelCategoryAssociate.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabelCategoryAssociate.setText("Category :");

        jComboBoxCategory.setFont(new java.awt.Font("Dialog", 0, 12));
        jComboBoxCategory.setToolTipText("Category of the subject");

        jButtonClose.setText("Close");
        jButtonClose.setToolTipText("Close");
        jButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabellTitle)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDescription)
                            .addComponent(jLabelName)
                            .addComponent(jLabelCategoryAssociate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jTextName, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jComboBoxCategory, 0, 232, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabellTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCategoryAssociate)
                    .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescription)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonAdd))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseClicked
        Category categorySelected = (Category) jComboBoxCategory.getSelectedItem();
        if (checkField(jTextName)) {
            Subject subject = new Subject(jTextName.getText(), jTextAreaDescription.getText(), categorySelected);
            ApplicationEventsDispatcher.getApplicationEventsDispatcher().fireAddSubjectEvent(new SubjectEvent(evt, subject));
            this.getParent().remove(this); // Close panel
        }
    }//GEN-LAST:event_jButtonAddMouseClicked

    private Boolean checkField(JTextField field) {
        if (field.getText().isEmpty()) {
            field.setBorder(BorderFactory.createLineBorder(Color.RED));
            field.setText("This field have to be fill");
            return false;
        } else {
            for (Subject s : Subjects.getInstance().getSubjects()) {
                if (s.getName().equals(field.getText())) {
                    javax.swing.JOptionPane.showMessageDialog(null, "This subject is already exists");
                    return false;
                }
            }
            return true;
        }
    }

    private void jButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseClicked
        this.getParent().remove(this); // Close panel
    }//GEN-LAST:event_jButtonCloseMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JComboBox jComboBoxCategory;
    private javax.swing.JLabel jLabelCategoryAssociate;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabellTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextName;
    // End of variables declaration//GEN-END:variables
}
