/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JCategoriePanel.java
 *
 * Created on 14 oct. 2009, 11:46:50
 */
package fr.enib.ihm.bookshop.view;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.BorderFactory;
import com.birosoft.liquid.borders.LiquidTextFieldBorder;
import java.text.DateFormat;

/**
 *
 * @author yo8chapa
 */
public class JEditOrderPanel extends javax.swing.JPanel {

    /** Creates new form JCategoriePanel */
    private static final String birthRegex = "([0-9]{2}/){2}[0-9]{4}";
    private JDateChooser calendar = null;

    public JEditOrderPanel() {
        initComponents();
        calendar = new JDateChooser("dd/MM/yyyy", "##/##/####", '_');
        jPanelDate.add(calendar);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbLTitleNorth = new javax.swing.JLabel();
        jPanelFooter = new javax.swing.JPanel();
        jPanelFind = new javax.swing.JPanel();
        jButtonFind = new javax.swing.JButton();
        jPanelCRUD = new javax.swing.JPanel();
        jButtonCreate = new javax.swing.JButton();
        jButtonRead = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jPanelClose = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();
        jPanelCenter = new javax.swing.JPanel();
        jLblOrderDate = new javax.swing.JLabel();
        jLblCustomer = new javax.swing.JLabel();
        jLblBook = new javax.swing.JLabel();
        jLblQuantity = new javax.swing.JLabel();
        jCmboCustomer = new javax.swing.JComboBox();
        jGrpBoxInf = new javax.swing.JPanel();
        jLblPwd = new javax.swing.JLabel();
        jLblType = new javax.swing.JLabel();
        jLblExpiryDate = new javax.swing.JLabel();
        jPwdField16c = new javax.swing.JPasswordField();
        jCmboType = new javax.swing.JComboBox();
        jPanelDate = new javax.swing.JPanel();
        jPwdField3c = new javax.swing.JPasswordField();
        jComboBox2 = new javax.swing.JComboBox();
        jSpinnerQuantity = new javax.swing.JSpinner();
        jLblDateToday = new javax.swing.JLabel();

        setName("JMainPanel"); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(470, 522));
        setLayout(new java.awt.BorderLayout());

        jLbLTitleNorth.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLbLTitleNorth.setText("Order");
        jLbLTitleNorth.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(jLbLTitleNorth, java.awt.BorderLayout.NORTH);

        jPanelFooter.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelFooter.setOpaque(false);
        jPanelFooter.setLayout(new javax.swing.BoxLayout(jPanelFooter, javax.swing.BoxLayout.X_AXIS));

        jPanelFind.setOpaque(false);
        jPanelFind.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButtonFind.setText("Find");
        jPanelFind.add(jButtonFind);

        jPanelFooter.add(jPanelFind);

        jPanelCRUD.setOpaque(false);

        jButtonCreate.setText("Create");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });
        jPanelCRUD.add(jButtonCreate);

        jButtonRead.setText("Retrive");
        jPanelCRUD.add(jButtonRead);

        jButtonUpdate.setText("Update");
        jPanelCRUD.add(jButtonUpdate);

        jButtonDelete.setText("Delete");
        jPanelCRUD.add(jButtonDelete);

        jPanelFooter.add(jPanelCRUD);

        jPanelClose.setOpaque(false);
        jPanelClose.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonClose.setText("Close");
        jPanelClose.add(jButtonClose);

        jPanelFooter.add(jPanelClose);

        add(jPanelFooter, java.awt.BorderLayout.SOUTH);

        jLblOrderDate.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLblOrderDate.setText("Order Date");

        jLblCustomer.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLblCustomer.setText("Customer");

        jLblBook.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLblBook.setText("Book");

        jLblQuantity.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLblQuantity.setText("Quantity");

        jCmboCustomer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jGrpBoxInf.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Credit Card Informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLblPwd.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLblPwd.setText("Password");
        jLblPwd.setPreferredSize(new java.awt.Dimension(31, 15));

        jLblType.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLblType.setText("Type");
        jLblType.setPreferredSize(new java.awt.Dimension(31, 15));

        jLblExpiryDate.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLblExpiryDate.setText("Expiry Date");

        jPwdField16c.setColumns(16);
        jPwdField16c.setText("jPasswordField12");

        jCmboType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VISA", "Mastercard", "American Express", "JCB", "Diners" }));

        jPanelDate.setLayout(new java.awt.BorderLayout());

        jPwdField3c.setColumns(3);
        jPwdField3c.setText("000");

        javax.swing.GroupLayout jGrpBoxInfLayout = new javax.swing.GroupLayout(jGrpBoxInf);
        jGrpBoxInf.setLayout(jGrpBoxInfLayout);
        jGrpBoxInfLayout.setHorizontalGroup(
            jGrpBoxInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGrpBoxInfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jGrpBoxInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblExpiryDate)
                    .addGroup(jGrpBoxInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLblType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLblPwd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                .addGap(6, 6, 6)
                .addGroup(jGrpBoxInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmboType, 0, 163, Short.MAX_VALUE)
                    .addGroup(jGrpBoxInfLayout.createSequentialGroup()
                        .addComponent(jPwdField16c, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPwdField3c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jGrpBoxInfLayout.setVerticalGroup(
            jGrpBoxInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGrpBoxInfLayout.createSequentialGroup()
                .addGroup(jGrpBoxInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPwdField16c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPwdField3c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jGrpBoxInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jGrpBoxInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDate, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                    .addComponent(jLblExpiryDate))
                .addContainerGap())
        );

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLblDateToday.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLblDateToday.setText("01/01/2009");

        javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCenterLayout.createSequentialGroup()
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLblBook, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblCustomer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblOrderDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblDateToday, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCmboCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(633, Short.MAX_VALUE))
                    .addGroup(jPanelCenterLayout.createSequentialGroup()
                        .addComponent(jLblQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(921, 921, 921))
                    .addGroup(jPanelCenterLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jGrpBoxInf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblOrderDate)
                    .addComponent(jLblDateToday, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCustomer)
                    .addComponent(jCmboCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblBook)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jGrpBoxInf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblQuantity)
                    .addComponent(jSpinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(jPanelCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed

        if (((Integer) jSpinnerQuantity.getValue()).intValue() > 0) {
            jSpinnerQuantity.setBorder(new LiquidTextFieldBorder());
        } else {
            jSpinnerQuantity.setBorder(BorderFactory.createLineBorder(Color.red, 1));
        }
        if (jPwdField16c.getText().length() == 16) {
            jPwdField16c.setBorder(new LiquidTextFieldBorder());
        } else {
            jPwdField16c.setBorder(BorderFactory.createLineBorder(Color.red, 1));
        }
        if (jPwdField3c.getText().length() == 3) {
            jPwdField3c.setBorder(new LiquidTextFieldBorder());
        } else {
            jPwdField3c.setBorder(BorderFactory.createLineBorder(Color.red, 1));
        }
        if (new SimpleDateFormat("dd/MM/yyyy").format(calendar.getDate()).matches(birthRegex)) {
            //new Customer?
        } else {
            calendar.setBorder(BorderFactory.createLineBorder(Color.red, 1));
        }
    }//GEN-LAST:event_jButtonCreateActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonFind;
    private javax.swing.JButton jButtonRead;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox jCmboCustomer;
    private javax.swing.JComboBox jCmboType;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JPanel jGrpBoxInf;
    private javax.swing.JLabel jLbLTitleNorth;
    private javax.swing.JLabel jLblBook;
    private javax.swing.JLabel jLblCustomer;
    private javax.swing.JLabel jLblDateToday;
    private javax.swing.JLabel jLblExpiryDate;
    private javax.swing.JLabel jLblOrderDate;
    private javax.swing.JLabel jLblPwd;
    private javax.swing.JLabel jLblQuantity;
    private javax.swing.JLabel jLblType;
    private javax.swing.JPanel jPanelCRUD;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelClose;
    private javax.swing.JPanel jPanelDate;
    private javax.swing.JPanel jPanelFind;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPasswordField jPwdField16c;
    private javax.swing.JPasswordField jPwdField3c;
    private javax.swing.JSpinner jSpinnerQuantity;
    // End of variables declaration//GEN-END:variables
}
