/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JCategoriePanel.java
 *
 * Created on 14 oct. 2009, 11:46:50
 */
package fr.enib.ihm.bookshop.view;

import fr.enib.ihm.bookshop.controller.ApplicationEventsDispatcher;
import fr.enib.ihm.bookshop.controller.Orders;
import fr.enib.ihm.bookshop.controller.events.OrderEvent;
import fr.enib.ihm.bookshop.domain.order.Order;
import fr.enib.ihm.bookshop.view.subView.JClosePanel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author yo8chapa
 */
public class JOrderPanel extends javax.swing.JPanel {

    /** Creates new form JOrderPanel */
    public JOrderPanel() {
        initComponents();
        jMainTable.setModel(Orders.getInstance());
        jMainTable.addMouseListener(new MouseAdapter(){
        @Override
        public void mouseClicked(MouseEvent e){
        if (e.getClickCount() == 2){
            jButtonReadMouseClicked(e);
         }
        }
        });
       // TableCellRenderer headerRenderer = jMainTable.getTableHeader().getDefaultRenderer();
        //((DefaultTableCellRenderer) headerRenderer).setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbLTitleNorth = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jMainTable = new javax.swing.JTable();
        jPanelFooter = new javax.swing.JPanel();
        jPanelFind = new javax.swing.JPanel();
        jButtonFind = new javax.swing.JButton();
        jPanelCRUD = new javax.swing.JPanel();
        jButtonCreate = new javax.swing.JButton();
        jButtonRead = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jPanelClose = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();

        setName("JMainPanel"); // NOI18N
        setOpaque(false);
        setLayout(new java.awt.BorderLayout(0, 5));

        jLbLTitleNorth.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLbLTitleNorth.setText("Orders");
        jLbLTitleNorth.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(jLbLTitleNorth, java.awt.BorderLayout.NORTH);

        jScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jScrollPane.setOpaque(false);

        jMainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Order Date", "Customer's Full Name", "Quantity", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jMainTable.setName("jmainTable"); // NOI18N
        jScrollPane.setViewportView(jMainTable);

        add(jScrollPane, java.awt.BorderLayout.CENTER);

        jPanelFooter.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelFooter.setOpaque(false);
        jPanelFooter.setLayout(new javax.swing.BoxLayout(jPanelFooter, javax.swing.BoxLayout.X_AXIS));

        jPanelFind.setOpaque(false);
        jPanelFind.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButtonFind.setText("Find");
        jPanelFind.add(jButtonFind);

        jPanelFooter.add(jPanelFind);

        jPanelCRUD.setOpaque(false);

        jButtonCreate.setText("Create");
        jButtonCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCreateMouseClicked(evt);
            }
        });
        jPanelCRUD.add(jButtonCreate);

        jButtonRead.setText("Read");
        jButtonRead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonReadMouseClicked(evt);
            }
        });
        jPanelCRUD.add(jButtonRead);

        jButtonUpdate.setText("Update");
        jButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseClicked(evt);
            }
        });
        jPanelCRUD.add(jButtonUpdate);

        jButtonDelete.setText("Delete");
        jButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteMouseClicked(evt);
            }
        });
        jPanelCRUD.add(jButtonDelete);

        jPanelFooter.add(jPanelCRUD);

        jPanelClose.setOpaque(false);
        jPanelClose.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonClose.setText("Close");
        jButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseClicked(evt);
            }
        });
        jPanelClose.add(jButtonClose);

        jPanelFooter.add(jPanelClose);

        add(jPanelFooter, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreateMouseClicked
        JPanel createPanel = new JCreateOrderPanel();
        JTabbedPane tabbedPane = (JTabbedPane) getParent();
        new JClosePanel("Create new order", tabbedPane, createPanel);
        tabbedPane.setSelectedIndex(tabbedPane.indexOfComponent(createPanel));
    }//GEN-LAST:event_jButtonCreateMouseClicked

    private void jButtonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteMouseClicked
        int row = jMainTable.getSelectedRow();
        if (row >=0){
            Order order = Orders.getInstance().getOrderAtRow(row);
            ApplicationEventsDispatcher.getApplicationEventsDispatcher().fireRemoveOrderEvent(new OrderEvent(evt,order));
        }
    }//GEN-LAST:event_jButtonDeleteMouseClicked

    private void jButtonReadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReadMouseClicked
        int row = jMainTable.getSelectedRow();
        if (row >=0){
            JPanel readPanel = new JReadOrderPanel(Orders.getInstance().getOrderAtRow(row));
            JTabbedPane tabbedPane = (JTabbedPane) getParent();
            new JClosePanel("Read an order",tabbedPane, readPanel);
            tabbedPane.setSelectedIndex(tabbedPane.indexOfComponent(readPanel));
        }
    }//GEN-LAST:event_jButtonReadMouseClicked

    private void jButtonUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseClicked
        int row = jMainTable.getSelectedRow();
        if (row >=0){
            JPanel updatePanel = new JUpdateOrderPanel(Orders.getInstance().getOrderAtRow(row));
            JTabbedPane tabbedPane = (JTabbedPane) getParent();
            new JClosePanel("Update an order",tabbedPane, updatePanel);
            tabbedPane.setSelectedIndex(tabbedPane.indexOfComponent(updatePanel));
        }
    }//GEN-LAST:event_jButtonUpdateMouseClicked

    private void jButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseClicked
        getParent().remove(this);
    }//GEN-LAST:event_jButtonCloseMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonFind;
    private javax.swing.JButton jButtonRead;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLbLTitleNorth;
    private javax.swing.JTable jMainTable;
    private javax.swing.JPanel jPanelCRUD;
    private javax.swing.JPanel jPanelClose;
    private javax.swing.JPanel jPanelFind;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
}
