/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JEditBookPanel.java
 *
 * Created on 14 oct. 2009, 11:46:50
 */
package fr.enib.ihm.bookshop.view;

import com.toedter.calendar.JDateChooser;
import fr.enib.ihm.bookshop.domain.customer.Customer;
import fr.enib.ihm.bookshop.domain.order.Order;
import fr.enib.ihm.bookshop.domain.order.OrderLine;
import fr.enib.ihm.bookshop.view.subView.JClosePanel;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author yo8chapa
 */
public class JReadOrderPanel extends javax.swing.JPanel {

    /** Creates new form JReadOrderPanel */
    public JReadOrderPanel(Order order) {
        initComponents();
        /*
         * Initialisation
         */
        setOrderToRead(order);
        jLabelOrderId.setText("Order's id : " + String.valueOf(order.getId()));
        SimpleDateFormat d = new SimpleDateFormat("dd/MM/yyyy");
        String dateString = d.format(order.getOrderDate());
        jTextOrderDate.setText(dateString);
        // -- Panel hidden
        // Credit card
        if (order.getCreditCard().equals(order.getCustomer().getCreditCard())) {
            buttonGroupCreditCard.setSelected(jRadioButtonCustomerCard.getModel(), true);
            displayCardFields(false);
        } else {
            buttonGroupCreditCard.setSelected(jRadioButtonSpecifCard.getModel(), true);
            jTextCardNumber.setText(order.getCreditCard().getCreditCardNumber());
            jTextCardType.setText(order.getCreditCard().getCreditCardType());
            jTextDateExpiration.setText(order.getCreditCard().getCreditCardExpDate());
        }
        // Address
        if (order.getDeliveryAddress().equals(order.getCustomer().getAddress())) {
            buttonGroupAddress.setSelected(jRadioButtonCustomerAddress.getModel(), true);
            displayAddressFields(false);
        } else {
            buttonGroupAddress.setSelected(jRadioButtonSpecificAddress.getModel(), true);
            jTextStreetNumber.setText(String.valueOf(order.getDeliveryAddress().getStreetNumber()));
            jTextStreet.setText(order.getDeliveryAddress().getStreet());
            jTextCity.setText(order.getDeliveryAddress().getCity());
            jTextZcode.setText(order.getDeliveryAddress().getZipcode());
            jTextCountry.setText(order.getDeliveryAddress().getCountry());
        }
        // Customer
        jTextCustomer.setText(order.getCustomer().getFirstName() + " " + order.getCustomer().getLastName());
        // -- Order list
        for (OrderLine o : order.getOrderLines()) {
            orderList.add(o);
        }
        jListOrders.setListData(orderList);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAddress = new javax.swing.ButtonGroup();
        buttonGroupCreditCard = new javax.swing.ButtonGroup();
        jLbLTitleNorth = new javax.swing.JLabel();
        jPanelFooter = new javax.swing.JPanel();
        jPanelForm = new javax.swing.JPanel();
        jPanelBuyInformation = new javax.swing.JPanel();
        jPanelCreditCard = new javax.swing.JPanel();
        jLabelCardNumber = new javax.swing.JLabel();
        jTextCardNumber = new javax.swing.JTextField();
        jTextCardType = new javax.swing.JTextField();
        jLabelCardType = new javax.swing.JLabel();
        jLabelCardExpiration = new javax.swing.JLabel();
        jPanelBtRadioCard = new javax.swing.JPanel();
        jRadioButtonCustomerCard = new javax.swing.JRadioButton();
        jRadioButtonSpecifCard = new javax.swing.JRadioButton();
        jTextDateExpiration = new javax.swing.JTextField();
        jPanelAdress = new javax.swing.JPanel();
        jLabelStreet = new javax.swing.JLabel();
        jTextStreet = new javax.swing.JTextField();
        jLabelCity = new javax.swing.JLabel();
        jTextCity = new javax.swing.JTextField();
        jLabelZcode = new javax.swing.JLabel();
        jTextZcode = new javax.swing.JTextField();
        jLabelCountry = new javax.swing.JLabel();
        jTextCountry = new javax.swing.JTextField();
        jLabelStreetNumber = new javax.swing.JLabel();
        jTextStreetNumber = new javax.swing.JTextField();
        jPanelBtAddress = new javax.swing.JPanel();
        jRadioButtonCustomerAddress = new javax.swing.JRadioButton();
        jRadioButtonSpecificAddress = new javax.swing.JRadioButton();
        jLabelCustomer = new javax.swing.JLabel();
        jButtonReadCustomer = new javax.swing.JButton();
        jTextCustomer = new javax.swing.JTextField();
        jPanelClose = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();
        jPanelOrder = new javax.swing.JPanel();
        jPanelListOrderLine = new javax.swing.JPanel();
        jScrollPaneOrders = new javax.swing.JScrollPane();
        jListOrders = new javax.swing.JList();
        jLabelOrderDate = new javax.swing.JLabel();
        jTextOrderDate = new javax.swing.JTextField();
        jLabelOrderId = new javax.swing.JLabel();

        setName("JMainPanel"); // NOI18N
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jLbLTitleNorth.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLbLTitleNorth.setText("Create an order");
        jLbLTitleNorth.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(jLbLTitleNorth, java.awt.BorderLayout.NORTH);

        jPanelFooter.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelFooter.setOpaque(false);
        jPanelFooter.setLayout(new javax.swing.BoxLayout(jPanelFooter, javax.swing.BoxLayout.X_AXIS));
        add(jPanelFooter, java.awt.BorderLayout.SOUTH);

        jPanelForm.setOpaque(false);

        jPanelBuyInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "delivery's information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanelBuyInformation.setOpaque(false);

        jPanelCreditCard.setBackground(new java.awt.Color(204, 204, 204));
        jPanelCreditCard.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Credit card ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabelCardNumber.setText("Card number :");

        jTextCardNumber.setEditable(false);

        jTextCardType.setEditable(false);

        jLabelCardType.setText("Type :");

        jLabelCardExpiration.setText("Date expiration :");

        jPanelBtRadioCard.setOpaque(false);

        buttonGroupCreditCard.add(jRadioButtonCustomerCard);
        jRadioButtonCustomerCard.setText("Customer's credit card");
        jRadioButtonCustomerCard.setEnabled(false);
        jRadioButtonCustomerCard.setOpaque(false);
        jRadioButtonCustomerCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCustomerCardActionPerformed(evt);
            }
        });

        buttonGroupCreditCard.add(jRadioButtonSpecifCard);
        jRadioButtonSpecifCard.setText("Specific credit card");
        jRadioButtonSpecifCard.setEnabled(false);
        jRadioButtonSpecifCard.setOpaque(false);
        jRadioButtonSpecifCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSpecifCardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtRadioCardLayout = new javax.swing.GroupLayout(jPanelBtRadioCard);
        jPanelBtRadioCard.setLayout(jPanelBtRadioCardLayout);
        jPanelBtRadioCardLayout.setHorizontalGroup(
            jPanelBtRadioCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtRadioCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonCustomerCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonSpecifCard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBtRadioCardLayout.setVerticalGroup(
            jPanelBtRadioCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtRadioCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBtRadioCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCustomerCard)
                    .addComponent(jRadioButtonSpecifCard))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextDateExpiration.setEditable(false);

        javax.swing.GroupLayout jPanelCreditCardLayout = new javax.swing.GroupLayout(jPanelCreditCard);
        jPanelCreditCard.setLayout(jPanelCreditCardLayout);
        jPanelCreditCardLayout.setHorizontalGroup(
            jPanelCreditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreditCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCreditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBtRadioCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCreditCardLayout.createSequentialGroup()
                        .addGroup(jPanelCreditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCardExpiration)
                            .addGroup(jPanelCreditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelCardType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCardNumber)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCreditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextCardNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                            .addComponent(jTextCardType, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                            .addComponent(jTextDateExpiration))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanelCreditCardLayout.setVerticalGroup(
            jPanelCreditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreditCardLayout.createSequentialGroup()
                .addComponent(jPanelBtRadioCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCreditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCardNumber)
                    .addComponent(jTextCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCreditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCardType))
                .addGap(12, 12, 12)
                .addGroup(jPanelCreditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCardExpiration)
                    .addComponent(jTextDateExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanelAdress.setBackground(new java.awt.Color(204, 204, 204));
        jPanelAdress.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Adress ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabelStreet.setText("Street :");

        jTextStreet.setEditable(false);

        jLabelCity.setText("City :");

        jTextCity.setEditable(false);

        jLabelZcode.setText("Zip code :");

        jTextZcode.setEditable(false);

        jLabelCountry.setText("Country");

        jTextCountry.setEditable(false);

        jLabelStreetNumber.setText("Number :");

        jTextStreetNumber.setEditable(false);

        jPanelBtAddress.setOpaque(false);

        buttonGroupAddress.add(jRadioButtonCustomerAddress);
        jRadioButtonCustomerAddress.setText("Customer's address");
        jRadioButtonCustomerAddress.setEnabled(false);
        jRadioButtonCustomerAddress.setOpaque(false);
        jRadioButtonCustomerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCustomerAddressActionPerformed(evt);
            }
        });

        buttonGroupAddress.add(jRadioButtonSpecificAddress);
        jRadioButtonSpecificAddress.setText("Specific address");
        jRadioButtonSpecificAddress.setEnabled(false);
        jRadioButtonSpecificAddress.setOpaque(false);
        jRadioButtonSpecificAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSpecificAddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtAddressLayout = new javax.swing.GroupLayout(jPanelBtAddress);
        jPanelBtAddress.setLayout(jPanelBtAddressLayout);
        jPanelBtAddressLayout.setHorizontalGroup(
            jPanelBtAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtAddressLayout.createSequentialGroup()
                .addComponent(jRadioButtonCustomerAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonSpecificAddress)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanelBtAddressLayout.setVerticalGroup(
            jPanelBtAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtAddressLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBtAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCustomerAddress)
                    .addComponent(jRadioButtonSpecificAddress)))
        );

        javax.swing.GroupLayout jPanelAdressLayout = new javax.swing.GroupLayout(jPanelAdress);
        jPanelAdress.setLayout(jPanelAdressLayout);
        jPanelAdressLayout.setHorizontalGroup(
            jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAdressLayout.createSequentialGroup()
                        .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStreet)
                            .addComponent(jLabelCountry)
                            .addComponent(jLabelCity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCountry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(jTextCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(jTextStreet, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelZcode)
                            .addComponent(jLabelStreetNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextZcode)
                            .addComponent(jTextStreetNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelAdressLayout.setVerticalGroup(
            jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdressLayout.createSequentialGroup()
                .addComponent(jPanelBtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStreet)
                    .addComponent(jTextStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextStreetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStreetNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCity)
                    .addComponent(jTextCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextZcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelZcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCountry)
                    .addComponent(jTextCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        jLabelCustomer.setText("Customer : ");

        jButtonReadCustomer.setText("See customer's data");
        jButtonReadCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonReadCustomerMouseClicked(evt);
            }
        });

        jTextCustomer.setEditable(false);

        javax.swing.GroupLayout jPanelBuyInformationLayout = new javax.swing.GroupLayout(jPanelBuyInformation);
        jPanelBuyInformation.setLayout(jPanelBuyInformationLayout);
        jPanelBuyInformationLayout.setHorizontalGroup(
            jPanelBuyInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuyInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuyInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAdress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCreditCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelBuyInformationLayout.createSequentialGroup()
                        .addComponent(jLabelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReadCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelBuyInformationLayout.setVerticalGroup(
            jPanelBuyInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuyInformationLayout.createSequentialGroup()
                .addGroup(jPanelBuyInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCustomer)
                    .addComponent(jButtonReadCustomer)
                    .addComponent(jTextCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCreditCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelClose.setOpaque(false);
        jPanelClose.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonClose.setText("Close");
        jButtonClose.setToolTipText("Close this panel");
        jButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseClicked(evt);
            }
        });
        jPanelClose.add(jButtonClose);

        jPanelOrder.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Order ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jListOrders.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListOrders.setToolTipText("Order line's list");
        jScrollPaneOrders.setViewportView(jListOrders);

        jLabelOrderDate.setText("Order's date : ");

        jTextOrderDate.setEnabled(false);

        jLabelOrderId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOrderId.setText("Id :");

        javax.swing.GroupLayout jPanelListOrderLineLayout = new javax.swing.GroupLayout(jPanelListOrderLine);
        jPanelListOrderLine.setLayout(jPanelListOrderLineLayout);
        jPanelListOrderLineLayout.setHorizontalGroup(
            jPanelListOrderLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListOrderLineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListOrderLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(jLabelOrderId)
                    .addGroup(jPanelListOrderLineLayout.createSequentialGroup()
                        .addComponent(jLabelOrderDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelListOrderLineLayout.setVerticalGroup(
            jPanelListOrderLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListOrderLineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelOrderId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelListOrderLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOrderDate)
                    .addComponent(jTextOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelOrderLayout = new javax.swing.GroupLayout(jPanelOrder);
        jPanelOrder.setLayout(jPanelOrderLayout);
        jPanelOrderLayout.setHorizontalGroup(
            jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListOrderLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelOrderLayout.setVerticalGroup(
            jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrderLayout.createSequentialGroup()
                .addComponent(jPanelListOrderLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelFormLayout = new javax.swing.GroupLayout(jPanelForm);
        jPanelForm.setLayout(jPanelFormLayout);
        jPanelFormLayout.setHorizontalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addComponent(jPanelBuyInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanelOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelFormLayout.setVerticalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelBuyInformation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );

        add(jPanelForm, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void displayAddressFields(Boolean b) {
        jTextStreet.setEnabled(b);
        jTextStreetNumber.setEnabled(b);
        jTextCity.setEnabled(b);
        jTextCountry.setEnabled(b);
        jTextZcode.setEnabled(b);
    }

    private void displayCardFields(Boolean b) {
        jTextCardNumber.setEnabled(b);
        jTextCardType.setEnabled(b);
    }
    private void jButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseClicked
        this.getParent().remove(this); // Close panel
    }//GEN-LAST:event_jButtonCloseMouseClicked

    private void jRadioButtonCustomerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCustomerAddressActionPerformed
        displayAddressFields(false);
    }//GEN-LAST:event_jRadioButtonCustomerAddressActionPerformed

    private void jRadioButtonSpecificAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSpecificAddressActionPerformed
        displayAddressFields(true);
    }//GEN-LAST:event_jRadioButtonSpecificAddressActionPerformed

    private void jRadioButtonCustomerCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCustomerCardActionPerformed
        displayCardFields(false);
    }//GEN-LAST:event_jRadioButtonCustomerCardActionPerformed

    private void jRadioButtonSpecifCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSpecifCardActionPerformed
        displayCardFields(true);
    }//GEN-LAST:event_jRadioButtonSpecifCardActionPerformed

    private void jButtonReadCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReadCustomerMouseClicked
        Customer customerSelectionnated = orderToRead.getCustomer();
        JPanel readPanel = new JReadCustomerPanel(customerSelectionnated);
        JTabbedPane tabbedPane = (JTabbedPane) getParent();
        new JClosePanel("Customer's data", tabbedPane, readPanel);
        tabbedPane.setSelectedIndex(tabbedPane.indexOfComponent(readPanel));
}//GEN-LAST:event_jButtonReadCustomerMouseClicked

    // -- Verifications
    private Boolean verifyCustomerCard() {
        Boolean retour = true;
        Date today = new Date();
        if (!calendarExpCardDate.getDate().after(today)) {
            calendarExpCardDate.setBorder(BorderFactory.createLineBorder(Color.RED));
            retour &= false;
        } else {
            calendarExpCardDate.setBorder(BorderFactory.createLineBorder(Color.GREEN));
        }
        retour &= verifyField(jTextCardNumber);
        return retour;
    }
    //

    private Boolean verifyField(JTextField name) {
        if (name.getText().isEmpty() == true) {
            name.setBorder(BorderFactory.createLineBorder(Color.RED));
            return new Boolean(false);
        } else {
            name.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            return new Boolean(true);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAddress;
    private javax.swing.ButtonGroup buttonGroupCreditCard;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonReadCustomer;
    private javax.swing.JLabel jLabelCardExpiration;
    private javax.swing.JLabel jLabelCardNumber;
    private javax.swing.JLabel jLabelCardType;
    private javax.swing.JLabel jLabelCity;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelCustomer;
    private javax.swing.JLabel jLabelOrderDate;
    private javax.swing.JLabel jLabelOrderId;
    private javax.swing.JLabel jLabelStreet;
    private javax.swing.JLabel jLabelStreetNumber;
    private javax.swing.JLabel jLabelZcode;
    private javax.swing.JLabel jLbLTitleNorth;
    private javax.swing.JList jListOrders;
    private javax.swing.JPanel jPanelAdress;
    private javax.swing.JPanel jPanelBtAddress;
    private javax.swing.JPanel jPanelBtRadioCard;
    private javax.swing.JPanel jPanelBuyInformation;
    private javax.swing.JPanel jPanelClose;
    private javax.swing.JPanel jPanelCreditCard;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JPanel jPanelListOrderLine;
    private javax.swing.JPanel jPanelOrder;
    private javax.swing.JRadioButton jRadioButtonCustomerAddress;
    private javax.swing.JRadioButton jRadioButtonCustomerCard;
    private javax.swing.JRadioButton jRadioButtonSpecifCard;
    private javax.swing.JRadioButton jRadioButtonSpecificAddress;
    private javax.swing.JScrollPane jScrollPaneOrders;
    private javax.swing.JTextField jTextCardNumber;
    private javax.swing.JTextField jTextCardType;
    private javax.swing.JTextField jTextCity;
    private javax.swing.JTextField jTextCountry;
    private javax.swing.JTextField jTextCustomer;
    private javax.swing.JTextField jTextDateExpiration;
    private javax.swing.JTextField jTextOrderDate;
    private javax.swing.JTextField jTextStreet;
    private javax.swing.JTextField jTextStreetNumber;
    private javax.swing.JTextField jTextZcode;
    // End of variables declaration//GEN-END:variables
    private JDateChooser calendarExpCardDate;
    private Vector orderList = new Vector();
    private Order orderToRead;

    public void setOrderToRead(Order orderToRead) {
        this.orderToRead = orderToRead;
    }
}
