/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JCategoriePanel.java
 *
 * Created on 14 oct. 2009, 11:46:50
 */

package fr.enib.ihm.bookshop.view;

import fr.enib.ihm.bookshop.controller.ApplicationEventsDispatcher;
import fr.enib.ihm.bookshop.controller.Subjects;
import fr.enib.ihm.bookshop.controller.events.SubjectEvent;
import fr.enib.ihm.bookshop.domain.catalog.Subject;
import fr.enib.ihm.bookshop.view.subView.JClosePanel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author yo8chapa
 */
public class JSubjectPanel extends javax.swing.JPanel {

    /** Creates new form JCategoriePanel */
    public JSubjectPanel() {
        initComponents();
        enableSearch(false);
        jMainTable.setModel(Subjects.getInstance());
        jMainTable.addMouseListener(new MouseAdapter(){
        @Override
        public void mouseClicked(MouseEvent e){
        if (e.getClickCount() == 2){
            jButtonReadMouseClicked(e);
         }
        }
        });

        //jMainTable.setAutoCreateRowSorter(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbLTitleNorth = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jMainTable = new javax.swing.JTable();
        jPanelFooter = new javax.swing.JPanel();
        jPanelFind = new javax.swing.JPanel();
        jButtonFind = new javax.swing.JButton();
        jTextSearch = new javax.swing.JTextField();
        jButtonValidateSearch = new javax.swing.JButton();
        jPanelCRUD = new javax.swing.JPanel();
        jButtonCreate = new javax.swing.JButton();
        jButtonRead = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jPanelClose = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();

        setName("JMainPanel"); // NOI18N
        setOpaque(false);
        setLayout(new java.awt.BorderLayout(0, 5));

        jLbLTitleNorth.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLbLTitleNorth.setText("Subjects");
        jLbLTitleNorth.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(jLbLTitleNorth, java.awt.BorderLayout.NORTH);

        jScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jScrollPane.setOpaque(false);

        jMainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jMainTable.setName("jmainTable"); // NOI18N
        jMainTable.setOpaque(false);
        jScrollPane.setViewportView(jMainTable);

        add(jScrollPane, java.awt.BorderLayout.CENTER);

        jPanelFooter.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelFooter.setOpaque(false);
        jPanelFooter.setLayout(new javax.swing.BoxLayout(jPanelFooter, javax.swing.BoxLayout.X_AXIS));

        jPanelFind.setOpaque(false);
        jPanelFind.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButtonFind.setText("Find");
        jButtonFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFindMouseClicked(evt);
            }
        });
        jPanelFind.add(jButtonFind);

        jTextSearch.setText("Search by name...");
        jTextSearch.setToolTipText("Search a subject by name");
        jTextSearch.setPreferredSize(new java.awt.Dimension(110, 20));
        jPanelFind.add(jTextSearch);

        jButtonValidateSearch.setText("ok");
        jButtonValidateSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonValidateSearchMouseClicked(evt);
            }
        });
        jPanelFind.add(jButtonValidateSearch);

        jPanelFooter.add(jPanelFind);

        jPanelCRUD.setOpaque(false);

        jButtonCreate.setText("Create");
        jButtonCreate.setToolTipText("Create a new subject");
        jButtonCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCreateMouseClicked(evt);
            }
        });
        jPanelCRUD.add(jButtonCreate);

        jButtonRead.setText("Read");
        jButtonRead.setToolTipText("Read the subject selectionnated");
        jButtonRead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonReadMouseClicked(evt);
            }
        });
        jPanelCRUD.add(jButtonRead);

        jButtonUpdate.setText("Update");
        jButtonUpdate.setToolTipText("update the subject selectionnated");
        jButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseClicked(evt);
            }
        });
        jPanelCRUD.add(jButtonUpdate);

        jButtonDelete.setText("Delete");
        jButtonDelete.setToolTipText("delete the subject selectionnated");
        jButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteMouseClicked(evt);
            }
        });
        jPanelCRUD.add(jButtonDelete);

        jPanelFooter.add(jPanelCRUD);

        jPanelClose.setOpaque(false);
        jPanelClose.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonClose.setText("Close");
        jButtonClose.setToolTipText("close this panel");
        jButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseClicked(evt);
            }
        });
        jPanelClose.add(jButtonClose);

        jPanelFooter.add(jPanelClose);

        add(jPanelFooter, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreateMouseClicked
        JPanel createPanel = new JCreateSubjectPanel();
        JTabbedPane tabbedPane = (JTabbedPane) getParent();
        new JClosePanel("Create new subject", tabbedPane, createPanel);
        tabbedPane.setSelectedIndex(tabbedPane.indexOfComponent(createPanel));
    }//GEN-LAST:event_jButtonCreateMouseClicked

    private void jButtonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteMouseClicked
        int row = jMainTable.getSelectedRow();        
        if (row >=0){
            Subject rmvObject = Subjects.getInstance().getSubjectAtRow(row);//jMainTable.getSelectedRow()
            //int id = (Integer) jMainTable.getValueAt(row, 0);
            ApplicationEventsDispatcher.getApplicationEventsDispatcher().fireRemoveSubjectEvent(new SubjectEvent(evt, rmvObject)); //, id
            jMainTable.updateUI();
        }
    }//GEN-LAST:event_jButtonDeleteMouseClicked

    private void jButtonUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseClicked
        int row = jMainTable.getSelectedRow();
        if (row >=0){            
            JPanel updatePanel = new JUpdateSubjectPanel(Subjects.getInstance().getSubjectAtRow(row));
            JTabbedPane tabbedPane = (JTabbedPane) getParent();
            new JClosePanel("Update a subject",tabbedPane, updatePanel);
            tabbedPane.setSelectedIndex(tabbedPane.indexOfComponent(updatePanel));
        }
    }//GEN-LAST:event_jButtonUpdateMouseClicked

    private void jButtonReadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReadMouseClicked
        int row = jMainTable.getSelectedRow();
        if (row >=0){           
            JPanel updatePanel = new JReadSubjectPanel(Subjects.getInstance().getSubjectAtRow(row));
            JTabbedPane tabbedPane = (JTabbedPane) getParent();
            new JClosePanel("Read a subject",tabbedPane, updatePanel);
            tabbedPane.setSelectedIndex(tabbedPane.indexOfComponent(updatePanel));
        }
    }//GEN-LAST:event_jButtonReadMouseClicked

    private void jButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseClicked
        this.getParent().remove(this); // Close panel
    }//GEN-LAST:event_jButtonCloseMouseClicked

    private void jButtonValidateSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonValidateSearchMouseClicked
        // -- Search
        for(Subject c : Subjects.getInstance().getSubjects()){
            if(c.getName().equals(jTextSearch.getText())){
                jMainTable.setRowSelectionInterval(c.getId()-1, c.getId()-1);
                enableSearch(false);
            }
        }
        jTextSearch.setText("Not found ...");
    }//GEN-LAST:event_jButtonValidateSearchMouseClicked

    private void jButtonFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFindMouseClicked
        enableSearch(true);
    }//GEN-LAST:event_jButtonFindMouseClicked
    private void enableSearch(Boolean b){
        jTextSearch.setVisible(b);
        jButtonFind.setVisible(!b);
        jButtonValidateSearch.setVisible(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonFind;
    private javax.swing.JButton jButtonRead;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonValidateSearch;
    private javax.swing.JLabel jLbLTitleNorth;
    private javax.swing.JTable jMainTable;
    private javax.swing.JPanel jPanelCRUD;
    private javax.swing.JPanel jPanelClose;
    private javax.swing.JPanel jPanelFind;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField jTextSearch;
    // End of variables declaration//GEN-END:variables

}
