/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JUpdateBookPanel.java
 *
 * Created on 14 oct. 2009, 11:46:50
 */

package fr.enib.ihm.bookshop.view;

import com.toedter.calendar.JDateChooser;
import fr.enib.ihm.bookshop.controller.ApplicationEventsDispatcher;
import fr.enib.ihm.bookshop.controller.Subjects;
import fr.enib.ihm.bookshop.controller.events.BookEvent;
import fr.enib.ihm.bookshop.domain.catalog.Book;
import fr.enib.ihm.bookshop.domain.catalog.Subject;
import java.awt.Color;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JTextField;

/**
 *
 * @author yo8chapa
 */
public class JUpdateBookPanel extends javax.swing.JPanel {

    /** Creates new form JEditBookPanel */
    public JUpdateBookPanel(Book b) {
        initComponents();
        calendar = new JDateChooser("dd/MM/yyyy", "##/##/####", '_');
        jPanelDateChooser.add(calendar);
        this.setBookToUpdated(b);
        jTextTitle.setText(bookToUpdated.getTitle());
        jTextIsbn.setText(bookToUpdated.getIsbn());
        if(bookToUpdated.getDateOfParution() == null)  calendar.setDate(new Date());
        else  calendar.setDate(bookToUpdated.getDateOfParution());
        jTextLang.setText(bookToUpdated.getLang());
        jTextAuthor.setText(bookToUpdated.getAuthor());
        jTextEditor.setText(bookToUpdated.getEditor());
        jTextPrice.setText(bookToUpdated.getPrice().toString());
        jTextImagePath.setText(bookToUpdated.getImagePath());
        for(Subject s: Subjects.getInstance().getSubjects()){
            jComboBoxSubject.addItem(s);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbLTitleNorth = new javax.swing.JLabel();
        jPanelFooter = new javax.swing.JPanel();
        jPanelClose = new javax.swing.JPanel();
        jButtonUpdate = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jPanelForm = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelIsbn = new javax.swing.JLabel();
        jLabelLang = new javax.swing.JLabel();
        jLabelAuthor = new javax.swing.JLabel();
        jLabelEditor = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabelDateParution = new javax.swing.JLabel();
        jLabelImagePath = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextTitle = new javax.swing.JTextField();
        jComboBoxSubject = new javax.swing.JComboBox();
        jTextIsbn = new javax.swing.JTextField();
        jTextLang = new javax.swing.JTextField();
        jTextAuthor = new javax.swing.JTextField();
        jTextEditor = new javax.swing.JTextField();
        jTextPrice = new javax.swing.JTextField();
        jTextImagePath = new javax.swing.JTextField();
        jPanelDateChooser = new javax.swing.JPanel();

        setName("JMainPanel"); // NOI18N
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jLbLTitleNorth.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLbLTitleNorth.setText("Update a book");
        jLbLTitleNorth.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(jLbLTitleNorth, java.awt.BorderLayout.NORTH);

        jPanelFooter.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelFooter.setOpaque(false);
        jPanelFooter.setLayout(new javax.swing.BoxLayout(jPanelFooter, javax.swing.BoxLayout.X_AXIS));

        jPanelClose.setOpaque(false);
        jPanelClose.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonUpdate.setText("Update");
        jButtonUpdate.setToolTipText("Create a book");
        jButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseClicked(evt);
            }
        });
        jPanelClose.add(jButtonUpdate);

        jButtonClose.setText("Close");
        jButtonClose.setToolTipText("Close this panel");
        jButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseClicked(evt);
            }
        });
        jPanelClose.add(jButtonClose);

        jPanelFooter.add(jPanelClose);

        add(jPanelFooter, java.awt.BorderLayout.SOUTH);

        jPanelForm.setOpaque(false);

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabelTitle.setText("Title");

        jLabelIsbn.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabelIsbn.setText("ISNB");

        jLabelLang.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabelLang.setText("Lang");

        jLabelAuthor.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabelAuthor.setText("Author");

        jLabelEditor.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabelEditor.setText("Editor");

        jLabelPrice.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabelPrice.setText("Price");

        jLabelDateParution.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabelDateParution.setText("Date of Parution");

        jLabelImagePath.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabelImagePath.setText("Image path");

        jLabel1.setText("Subject");

        jPanelDateChooser.setFocusable(false);
        jPanelDateChooser.setMaximumSize(new java.awt.Dimension(145, 15));
        jPanelDateChooser.setOpaque(false);
        jPanelDateChooser.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanelFormLayout = new javax.swing.GroupLayout(jPanelForm);
        jPanelForm.setLayout(jPanelFormLayout);
        jPanelFormLayout.setHorizontalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addComponent(jLabelImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jTextImagePath, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrice)
                            .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelEditor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelAuthor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                            .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelLang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabelIsbn)
                            .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDateParution, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                            .addComponent(jTextEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                            .addComponent(jTextPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                            .addComponent(jTextAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                            .addComponent(jTextLang, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                            .addComponent(jTextIsbn, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                            .addComponent(jComboBoxSubject, 0, 405, Short.MAX_VALUE)
                            .addComponent(jPanelDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanelFormLayout.setVerticalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addComponent(jTextTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIsbn)
                    .addComponent(jTextIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLang)
                    .addComponent(jTextLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAuthor)
                    .addComponent(jTextAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEditor)
                    .addComponent(jTextEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrice)
                    .addComponent(jTextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDateParution)
                    .addComponent(jPanelDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelImagePath)
                    .addComponent(jTextImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanelForm, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseClicked
        Boolean formOk = true; //Pour la vérification
        Subject subjectSelected = (Subject) jComboBoxSubject.getSelectedItem();
        if(subjectSelected != null)  formOk = false;
        String title = jTextTitle.getText();
        String lang = jTextLang.getText();
        String author = jTextAuthor.getText();
        String editor = jTextEditor.getText();
        Float price = new Float (0.0);
        if (jTextPrice.getText().isEmpty() != true){
            price = Float.valueOf(jTextPrice.getText());
        }            
        Date dateParution = calendar.getDate();
        // Vérification des champs
        formOk = verifyField(jTextTitle);
        formOk = verifyField(jTextLang);
        formOk = verifyField(jTextAuthor);
        //
        if(formOk == true){
            Book book = new Book(title, jTextIsbn.getText(), lang, dateParution, author, editor, price, jTextImagePath.getText(), subjectSelected);
            //book.setEditor(editor);
            //book.setSubject(subjectSelected);
            book.setId(bookToUpdated.getId());
            ApplicationEventsDispatcher.getApplicationEventsDispatcher().fireUpdateBookEvent(new BookEvent(evt, book));
            this.getParent().remove(this);
       }
}//GEN-LAST:event_jButtonUpdateMouseClicked

    private void jButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseClicked
        this.getParent().remove(this); // Close panel
    }//GEN-LAST:event_jButtonCloseMouseClicked

    private Boolean verifyField(JTextField name){
         if(name.getText().isEmpty() == true){
            name.setBorder(BorderFactory.createLineBorder(Color.RED));
            return new Boolean(false);
        }
        else{             
             name.setBorder(BorderFactory.createLineBorder(Color.BLACK));
             return new Boolean(true);
         }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox jComboBoxSubject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAuthor;
    private javax.swing.JLabel jLabelDateParution;
    private javax.swing.JLabel jLabelEditor;
    private javax.swing.JLabel jLabelImagePath;
    private javax.swing.JLabel jLabelIsbn;
    private javax.swing.JLabel jLabelLang;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLbLTitleNorth;
    private javax.swing.JPanel jPanelClose;
    private javax.swing.JPanel jPanelDateChooser;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JTextField jTextAuthor;
    private javax.swing.JTextField jTextEditor;
    private javax.swing.JTextField jTextImagePath;
    private javax.swing.JTextField jTextIsbn;
    private javax.swing.JTextField jTextLang;
    private javax.swing.JTextField jTextPrice;
    private javax.swing.JTextField jTextTitle;
    // End of variables declaration//GEN-END:variables
    private JDateChooser calendar;
    private Book bookToUpdated;

    public void setBookToUpdated(Book bookToUpdated) {
        this.bookToUpdated = bookToUpdated;
    }
}
