/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JUpdateCategoryPanel.java
 *
 * Created on 31 oct. 2009, 13:02:55
 */

package fr.enib.ihm.bookshop.view;

import fr.enib.ihm.bookshop.controller.ApplicationEventsDispatcher;
import fr.enib.ihm.bookshop.controller.events.CategoryEvent;
import fr.enib.ihm.bookshop.domain.catalog.Category;
import fr.enib.ihm.bookshop.domain.catalog.Subject;
import java.util.Vector;

/**
 *
 * @author Yoann
 */
public class JUpdateCategoryPanel extends javax.swing.JPanel {

    /** Creates new form JUpdateCategoryPanel */
    public JUpdateCategoryPanel(Category c){ //int id
        initComponents();
        this.setCategoryUpdated(c);
        jTextName.setText(categoryUpdated.getName());
        jTextAreaDescription.setText(categoryUpdated.getDescription());
        jLabelUpdatedCategoryId.setText("id : " + categoryUpdated.getId());        
        for(Subject subject : categoryUpdated.getSubjects()){
            categorySubjects.addElement(subject);
        }
        jListSubject.setListData(categorySubjects);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabellTitle = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jButtonAdd = new javax.swing.JButton();
        jLabelUpdatedCategoryId = new javax.swing.JLabel();
        jButtonClose = new javax.swing.JButton();
        jLabelSubject = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListSubject = new javax.swing.JList();

        jLabellTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabellTitle.setText("Update a category");
        jLabellTitle.setFocusable(false);

        jLabelDescription.setText("Description :");
        jLabelDescription.setFocusable(false);

        jLabelName.setText("Name : ");
        jLabelName.setFocusable(false);

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescription);

        jButtonAdd.setText("Update");
        jButtonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddMouseClicked(evt);
            }
        });

        jLabelUpdatedCategoryId.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabelUpdatedCategoryId.setForeground(new java.awt.Color(0, 102, 153));
        jLabelUpdatedCategoryId.setText("id :");
        jLabelUpdatedCategoryId.setToolTipText("updated category's id");
        jLabelUpdatedCategoryId.setFocusable(false);
        jLabelUpdatedCategoryId.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabelUpdatedCategoryId.setName("jLabelCategoryId"); // NOI18N

        jButtonClose.setText("Close");
        jButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseClicked(evt);
            }
        });

        jLabelSubject.setText("Subjects :");

        jListSubject.setEnabled(false);
        jScrollPane2.setViewportView(jListSubject);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabellTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                        .addComponent(jLabelUpdatedCategoryId))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDescription)
                            .addComponent(jLabelName)
                            .addComponent(jLabelSubject))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextName, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabellTitle)
                    .addComponent(jLabelUpdatedCategoryId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescription)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSubject)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonAdd))
                .addContainerGap())
        );

        jLabelUpdatedCategoryId.getAccessibleContext().setAccessibleName("jLabelCategoryId");
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseClicked
        categoryUpdated.setName(jTextName.getText());
        categoryUpdated.setDescription(jTextAreaDescription.getText());
        ApplicationEventsDispatcher.getApplicationEventsDispatcher().fireUpdateCategoryEvent(new CategoryEvent(evt,  categoryUpdated ));
        //new Category(categoryUpdated.getId(),jTextName.getText(), jTextAreaDescription.getText(), categorySubjects)
        this.getParent().remove(this); // Close panel
}//GEN-LAST:event_jButtonAddMouseClicked

    private void jButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseClicked
        this.getParent().remove(this); // Close panel
    }//GEN-LAST:event_jButtonCloseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelSubject;
    private javax.swing.JLabel jLabelUpdatedCategoryId;
    private javax.swing.JLabel jLabellTitle;
    private javax.swing.JList jListSubject;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextName;
    // End of variables declaration//GEN-END:variables
    private Category categoryUpdated;
    private Vector categorySubjects = new Vector();
    public void setCategoryUpdated(Category categoryUpdated) {
        this.categoryUpdated = categoryUpdated;
    }
}
