/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JEditBookPanel.java
 *
 * Created on 14 oct. 2009, 11:46:50
 */

package fr.enib.ihm.bookshop.view;

import com.toedter.calendar.JDateChooser;
import fr.enib.ihm.bookshop.controller.ApplicationEventsDispatcher;
import fr.enib.ihm.bookshop.controller.events.CustomerEvent;
import fr.enib.ihm.bookshop.domain.customer.Address;
import fr.enib.ihm.bookshop.domain.customer.CreditCard;
import fr.enib.ihm.bookshop.domain.customer.Customer;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JTextField;

/**
 *
 * @author yo8chapa
 */
public class JUpdateCustomerPanel extends javax.swing.JPanel {

    /** Creates new form JUpdateCustomerPanel */
    public JUpdateCustomerPanel(Customer c) throws ParseException {
        initComponents();
        setCustomerToUpdated(c);
        // -- Calendars // BirthDate and credit card expiration
        calendarBirthDate = new JDateChooser("dd/MM/yyyy", "##/##/####", '_');
        calendarBirthDate.setDate(c.getDateOfBirth());
        jPanelDateChooser.add(calendarBirthDate);
        calendarExpCardDate = new JDateChooser("dd/MM/yyyy", "##/##/####", '_');
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        calendarExpCardDate.setDate(formatter.parse(c.getCreditCard().getCreditCardExpDate()));
        jPanelDateCardChooser.add(calendarExpCardDate);
        // -- Customer information
        jLabelId.setText("Id : " + c.getId());
        jTextFirstName.setText(c.getFirstName());
        jTextLastName.setText(c.getLastName());
        jTextLogin.setText(c.getLogin());
        jTextPassword.setText(c.getPassword());
        jTextTelephone.setText(c.getTelephone());
        jTextMail.setText(c.getEmail());
        // -- Customer creditcard information
        jTextCardNumber.setText(c.getCreditCard().getCreditCardNumber());
        jTextCardType.setText(c.getCreditCard().getCreditCardType());
        // -- Customer adress information
        jTextStreet.setText(c.getAddress().getStreet());
        jTextStreetNumber.setText(String.valueOf(c.getAddress().getStreetNumber()));
        jTextCity.setText(c.getAddress().getCity());
        jTextZcode.setText(c.getAddress().getZipcode());
        jTextCountry.setText(c.getAddress().getCountry());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbLTitleNorth = new javax.swing.JLabel();
        jPanelFooter = new javax.swing.JPanel();
        jPanelForm = new javax.swing.JPanel();
        jPanelCustomer = new javax.swing.JPanel();
        jLabelFirstname = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jTextFirstName = new javax.swing.JTextField();
        jTextLastName = new javax.swing.JTextField();
        jTextLogin = new javax.swing.JTextField();
        jTextTelephone = new javax.swing.JTextField();
        jTextMail = new javax.swing.JTextField();
        jLabelLogin = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelTelephone = new javax.swing.JLabel();
        jLabelMail = new javax.swing.JLabel();
        jLabelDateBirth = new javax.swing.JLabel();
        jPanelDateChooser = new javax.swing.JPanel();
        jTextPassword = new javax.swing.JPasswordField();
        jLabelId = new javax.swing.JLabel();
        jPanelBuyInformation = new javax.swing.JPanel();
        jPanelCreditCard = new javax.swing.JPanel();
        jLabelCardNumber = new javax.swing.JLabel();
        jTextCardNumber = new javax.swing.JTextField();
        jTextCardType = new javax.swing.JTextField();
        jLabelCardType = new javax.swing.JLabel();
        jLabelCardExpiration = new javax.swing.JLabel();
        jPanelDateCardChooser = new javax.swing.JPanel();
        jPanelAdress = new javax.swing.JPanel();
        jLabelStreet = new javax.swing.JLabel();
        jTextStreet = new javax.swing.JTextField();
        jLabelCity = new javax.swing.JLabel();
        jTextCity = new javax.swing.JTextField();
        jLabelZcode = new javax.swing.JLabel();
        jTextZcode = new javax.swing.JTextField();
        jLabelCountry = new javax.swing.JLabel();
        jTextCountry = new javax.swing.JTextField();
        jLabelStreetNumber = new javax.swing.JLabel();
        jTextStreetNumber = new javax.swing.JTextField();
        jPanelClose = new javax.swing.JPanel();
        jButtonUpdate = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();

        setName("JMainPanel"); // NOI18N
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jLbLTitleNorth.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLbLTitleNorth.setText("Update customer");
        jLbLTitleNorth.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(jLbLTitleNorth, java.awt.BorderLayout.NORTH);

        jPanelFooter.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelFooter.setOpaque(false);
        jPanelFooter.setLayout(new javax.swing.BoxLayout(jPanelFooter, javax.swing.BoxLayout.X_AXIS));
        add(jPanelFooter, java.awt.BorderLayout.SOUTH);

        jPanelForm.setOpaque(false);

        jPanelCustomer.setBackground(new java.awt.Color(204, 204, 204));
        jPanelCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabelFirstname.setText("Firstname :");

        jLabelLastName.setText("Lastname :");

        jLabelLogin.setText("Login :");

        jLabelPassword.setText("Password :");

        jLabelTelephone.setText("Telephone :");

        jLabelMail.setText("E-mail :");

        jLabelDateBirth.setText("Date of birth :");

        jPanelDateChooser.setFocusable(false);
        jPanelDateChooser.setMaximumSize(new java.awt.Dimension(145, 15));
        jPanelDateChooser.setOpaque(false);
        jPanelDateChooser.setLayout(new java.awt.BorderLayout());

        jLabelId.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelId.setForeground(new java.awt.Color(0, 102, 204));
        jLabelId.setText("id : ");

        javax.swing.GroupLayout jPanelCustomerLayout = new javax.swing.GroupLayout(jPanelCustomer);
        jPanelCustomer.setLayout(jPanelCustomerLayout);
        jPanelCustomerLayout.setHorizontalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustomerLayout.createSequentialGroup()
                        .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFirstname)
                            .addComponent(jLabelLastName)
                            .addComponent(jLabelDateBirth)
                            .addComponent(jLabelLogin)
                            .addComponent(jLabelPassword)
                            .addComponent(jLabelTelephone)
                            .addComponent(jLabelMail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(jTextMail, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(jTextLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(jTextLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(jTextFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(jPanelDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(jTextPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
                    .addComponent(jLabelId, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelCustomerLayout.setVerticalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelId)
                .addGap(8, 8, 8)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFirstname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDateBirth)
                    .addComponent(jPanelDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jTextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelephone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMail))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanelBuyInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buy informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jPanelCreditCard.setBackground(new java.awt.Color(204, 204, 204));
        jPanelCreditCard.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Credit card ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabelCardNumber.setText("Card number :");

        jLabelCardType.setText("Type :");

        jLabelCardExpiration.setText("Date expiration :");

        jPanelDateCardChooser.setFocusable(false);
        jPanelDateCardChooser.setMaximumSize(new java.awt.Dimension(145, 15));
        jPanelDateCardChooser.setOpaque(false);
        jPanelDateCardChooser.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanelCreditCardLayout = new javax.swing.GroupLayout(jPanelCreditCard);
        jPanelCreditCard.setLayout(jPanelCreditCardLayout);
        jPanelCreditCardLayout.setHorizontalGroup(
            jPanelCreditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreditCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCreditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCardExpiration)
                    .addGroup(jPanelCreditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelCardType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCardNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCardNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(jTextCardType, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(jPanelDateCardChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCreditCardLayout.setVerticalGroup(
            jPanelCreditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreditCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCreditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCardNumber)
                    .addComponent(jTextCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCreditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCardType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreditCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCardExpiration)
                    .addComponent(jPanelDateCardChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAdress.setBackground(new java.awt.Color(204, 204, 204));
        jPanelAdress.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adress", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabelStreet.setText("Street :");

        jLabelCity.setText("City :");

        jLabelZcode.setText("Zip code :");

        jLabelCountry.setText("Country");

        jLabelStreetNumber.setText("Number :");

        javax.swing.GroupLayout jPanelAdressLayout = new javax.swing.GroupLayout(jPanelAdress);
        jPanelAdress.setLayout(jPanelAdressLayout);
        jPanelAdressLayout.setHorizontalGroup(
            jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStreet)
                    .addComponent(jLabelCountry)
                    .addComponent(jLabelCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCountry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jTextCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jTextStreet, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelZcode)
                    .addComponent(jLabelStreetNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextZcode)
                    .addComponent(jTextStreetNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelAdressLayout.setVerticalGroup(
            jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStreet)
                    .addComponent(jTextStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextStreetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStreetNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCity)
                    .addComponent(jTextCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextZcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelZcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCountry)
                    .addComponent(jTextCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelBuyInformationLayout = new javax.swing.GroupLayout(jPanelBuyInformation);
        jPanelBuyInformation.setLayout(jPanelBuyInformationLayout);
        jPanelBuyInformationLayout.setHorizontalGroup(
            jPanelBuyInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuyInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuyInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCreditCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAdress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelBuyInformationLayout.setVerticalGroup(
            jPanelBuyInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuyInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelClose.setOpaque(false);
        jPanelClose.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonUpdate.setText("Update");
        jButtonUpdate.setToolTipText("Update customer");
        jButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseClicked(evt);
            }
        });
        jPanelClose.add(jButtonUpdate);

        jButtonClose.setText("Close");
        jButtonClose.setToolTipText("Close this panel");
        jButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseClicked(evt);
            }
        });
        jPanelClose.add(jButtonClose);

        javax.swing.GroupLayout jPanelFormLayout = new javax.swing.GroupLayout(jPanelForm);
        jPanelForm.setLayout(jPanelFormLayout);
        jPanelFormLayout.setHorizontalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addComponent(jPanelCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelBuyInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelFormLayout.setVerticalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBuyInformation, javax.swing.GroupLayout.Alignment.TRAILING, 0, 305, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanelClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanelForm, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseClicked
        if(verifyCustomerData() & verifyCustomerCard()){
            // -- Définition de l'adresse
            int streetNumber = 0;
            if(!jTextStreetNumber.getText().isEmpty())  streetNumber = Integer.valueOf(jTextStreetNumber.getText());
            Address customerAddress = new Address( streetNumber, jTextStreet.getText(),
                                              jTextCity.getText(), jTextZcode.getText(), jTextCountry.getText());
            
            Customer customer = new Customer( jTextLogin.getText(),  jTextFirstName.getText(),  jTextLastName.getText(),
                                                 jTextTelephone.getText(),  jTextMail.getText(),  customerAddress);
            customer.setId(customerToUpdated.getId());
            customer.setPassword(jTextPassword.getText());
            customer.setDateOfBirth(calendarBirthDate.getDate());
            // -- Creditcard
            CreditCard customerCard = new CreditCard();
            customerCard.setCreditCardNumber(jTextCardNumber.getText());
            customerCard.setCreditCardType(jTextCardType.getText());
            SimpleDateFormat d = new SimpleDateFormat ("dd/MM/yyyy" );
            String dateString = d.format(this.calendarExpCardDate.getDate());
            customerCard.setCreditCardExpDate(dateString);
            customer.setCreditCard(customerCard);
               // -- Tirage d'évenement
               ApplicationEventsDispatcher.getApplicationEventsDispatcher().fireUpdateCustomerEvent(new CustomerEvent(evt, customer));
               this.getParent().remove(this); // Close panel
        }
}//GEN-LAST:event_jButtonUpdateMouseClicked

    private void jButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseClicked
        this.getParent().remove(this); // Close panel
    }//GEN-LAST:event_jButtonCloseMouseClicked

    // -- Verifications

         private Boolean verifyCustomerData(){
         // -- Le sous formulaire customer doit etre rempli
        Boolean retour = true;
        retour &= verifyField(jTextFirstName) & verifyField(jTextLastName);
        retour &= verifyField(jTextLogin) & verifyField(jTextPassword);
        retour &= verifyField(jTextMail);
        if(retour == true){
            // -- Tous les champs sont remplis, on vérifie leurs contenu
            // -- Mail
            if (!isEmailAdress(jTextMail.getText())){
                retour = false;
                jTextMail.setBorder(BorderFactory.createLineBorder( Color.red ));
                jTextMail.setText("Bad format - use username@host.xx");
            }
            else
                jTextMail.setBorder(BorderFactory.createLineBorder( Color.black ));
        }
        return retour;
    }
     private Boolean verifyCustomerCard(){
         Boolean retour = true;
         Date today = new Date();
         if(!calendarExpCardDate.getDate().after(today)){
            calendarExpCardDate.setBorder(BorderFactory.createLineBorder(Color.RED));
            retour &= false;
         }else {
             calendarExpCardDate.setBorder(BorderFactory.createLineBorder(Color.GREEN));
         }
         retour &= verifyField(jTextCardNumber);
         return retour;
     }
    //
    private Boolean verifyField(JTextField name){
         if(name.getText().isEmpty() == true){
            name.setBorder(BorderFactory.createLineBorder(Color.RED));
            return new Boolean(false);
        }
        else{             
             name.setBorder(BorderFactory.createLineBorder(Color.BLACK));
             return new Boolean(true);
         }
    }
    public static boolean isEmailAdress(String email){
        Pattern p = Pattern.compile(mailRegex);
        Matcher m = p.matcher(email.toUpperCase());
        return m.matches();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelCardExpiration;
    private javax.swing.JLabel jLabelCardNumber;
    private javax.swing.JLabel jLabelCardType;
    private javax.swing.JLabel jLabelCity;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelDateBirth;
    private javax.swing.JLabel jLabelFirstname;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelStreet;
    private javax.swing.JLabel jLabelStreetNumber;
    private javax.swing.JLabel jLabelTelephone;
    private javax.swing.JLabel jLabelZcode;
    private javax.swing.JLabel jLbLTitleNorth;
    private javax.swing.JPanel jPanelAdress;
    private javax.swing.JPanel jPanelBuyInformation;
    private javax.swing.JPanel jPanelClose;
    private javax.swing.JPanel jPanelCreditCard;
    private javax.swing.JPanel jPanelCustomer;
    private javax.swing.JPanel jPanelDateCardChooser;
    private javax.swing.JPanel jPanelDateChooser;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JTextField jTextCardNumber;
    private javax.swing.JTextField jTextCardType;
    private javax.swing.JTextField jTextCity;
    private javax.swing.JTextField jTextCountry;
    private javax.swing.JTextField jTextFirstName;
    private javax.swing.JTextField jTextLastName;
    private javax.swing.JTextField jTextLogin;
    private javax.swing.JTextField jTextMail;
    private javax.swing.JPasswordField jTextPassword;
    private javax.swing.JTextField jTextStreet;
    private javax.swing.JTextField jTextStreetNumber;
    private javax.swing.JTextField jTextTelephone;
    private javax.swing.JTextField jTextZcode;
    // End of variables declaration//GEN-END:variables
    private JDateChooser calendarBirthDate;
    private JDateChooser calendarExpCardDate;
    private static final String mailRegex = "^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,4}$";
    private Customer customerToUpdated;

    public void setCustomerToUpdated(Customer customerToUpdated) {
        this.customerToUpdated = customerToUpdated;
    }
}
